services:
  valkey:
    image: valkey/valkey:latest
    container_name: valkey-standalone
    command:
      - valkey-server
      - --appendonly
      - "yes"
    ports:
      - "6379:6379"
    networks:
      - valkey-net
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3

networks:
  valkey-net:
    driver: bridge